# Generated by Django 4.0.3 on 2023-03-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='name',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(default=12, max_length=17),
            preserve_default=False,
        ),
    ]
