# Generated by Django 4.0.3 on 2023-03-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_alter_salerecord_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecord',
            old_name='salesperson',
            new_name='sales_person',
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='potentialcustomer',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='employee_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
