# Generated by Django 4.0.3 on 2023-03-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='picture_url',
        ),
    ]
