# Generated by Django 4.0.3 on 2023-03-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_remove_technician_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
